// src/components/sections/eventsData.js

export const allEvents = [
  // Tokyo
  {
    id: 1,
    title: "Cherry Blossom Festival",
    location: "Tokyo",
    date: "March 25 - April 10, 2025",
    description: "Celebrate cherry blossoms at Ueno Park and Shinjuku Gyoen with picnics, night illuminations, and cultural performances.",
    cover: "https://images.unsplash.com/photo-1559910355-9b5e1971fae4?crop=entropy&cs=tinysrgb&fit=max&h=400&w=600",
    interest: "Festival",
    mapUrl: "https://goo.gl/maps/TokyoSakura",
  },
  {
    id: 2,
    title: "Tokyo Tower Light-Up",
    location: "Tokyo",
    date: "December 31, 2025",
    description: "Spectacular end-of-year Tokyo Tower light show with food stalls and street concerts.",
    cover: "https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80",
    interest: "Culture",
    mapUrl: "https://goo.gl/maps/TokyoTower",
  },
  // Kyoto
  {
    id: 3,
    title: "Gion Matsuri",
    location: "Kyoto",
    date: "July 1 - 31, 2025",
    description: "Grand processions of Yamaboko floats, traditional music and food stalls.",
    cover: "https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=600&q=80",
    interest: "Festival",
    mapUrl: "https://goo.gl/maps/KyotoGion",
  },
  {
    id: 4,
    title: "Philosopher's Path Hanami",
    location: "Kyoto",
    date: "April 10, 2025",
    description: "A picturesque walk along the Philosopher's Path during cherry blossom season.",
    cover: "https://images.unsplash.com/photo-1454023492550-5696f8ff10e1?auto=format&fit=crop&w=600&q=80",
    interest: "Culture",
    mapUrl: "https://goo.gl/maps/PhilosopherPath",
  },
  // Osaka
  {
    id: 5,
    title: "Osaka Castle Illuminations",
    location: "Osaka",
    date: "December 1 - December 31, 2025",
    description: "Winter illuminations at the iconic Osaka Castle—great for evening strolls and photos.",
    cover: "https://images.unsplash.com/photo-1601461367331-1e479d1d2ed0?auto=format&fit=crop&w=600&q=80",
    interest: "Culture",
    mapUrl: "https://goo.gl/maps/OsakaCastle",
  },
  {
    id: 6,
    title: "Osaka Food Street Fest",
    location: "Osaka",
    date: "May 15 - 18, 2025",
    description: "Sample takoyaki, kushikatsu, and local street eats along Dotonbori.",
    cover: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80",
    interest: "Festival",
    mapUrl: "https://goo.gl/maps/OsakaFoodFest",
  },
  // Nara
  {
    id: 7,
    title: "Nara Deer Festival",
    location: "Nara",
    date: "October 10, 2025",
    description: "Interact with sacred deer during this festival with local crafts and foods.",
    cover: "https://images.unsplash.com/photo-1589006860588-54d9056b98d2?auto=format&fit=crop&w=600&q=80",
    interest: "Culture",
    mapUrl: "https://goo.gl/maps/NaraDeer",
  },
  {
    id: 8,
    title: "Todai-ji Temple Lantern Night",
    location: "Nara",
    date: "August 8, 2025",
    description: "A serene night at the giant Buddha temple lit by glowing lanterns.",
    cover: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80",
    interest: "Festival",
    mapUrl: "https://goo.gl/maps/TodaiJiLantern",
  },
  // Hokkaido
  {
    id: 9,
    title: "Sapporo Snow Festival",
    location: "Hokkaido",
    date: "February 5 - 12, 2025",
    description: "Marvel at world-class snow and ice sculptures. Participate in snow-filled fun and local food tasting.",
    cover: "https://images.unsplash.com/photo-1578926373646-2e0b3cd5c23b?auto=format&fit=crop&w=600&q=80",
    interest: "Festival",
    mapUrl: "https://goo.gl/maps/HokkaidoSnow",
  },
  {
    id: 10,
    title: "Otaru Snow Light Path",
    location: "Hokkaido",
    date: "February 8 - 17, 2025",
    description: "Hundreds of lanterns and candles illuminate Otaru's snowy canals.",
    cover: "https://images.unsplash.com/photo-1465101162946-4377e57745c3?auto=format&fit=crop&w=600&q=80",
    interest: "Culture",
    mapUrl: "https://goo.gl/maps/OtaruLightPath",
  },
  // Okinawa
  {
    id: 11,
    title: "Okinawa Eisa Dance Festival",
    location: "Okinawa",
    date: "August 15 - 17, 2025",
    description: "Drumming and dance performances throughout Okinawa, celebrating its unique culture.",
    cover: "https://images.unsplash.com/photo-1525390002105-94d6f25e00aa?auto=format&fit=crop&w=600&q=80",
    interest: "Festival",
    mapUrl: "https://goo.gl/maps/OkinawaEisa",
  },
  {
    id: 12,
    title: "Okinawa Dragon Boat Race",
    location: "Okinawa",
    date: "May 5, 2025",
    description: "Traditional boat racing with parades, music, and local foods in Naha's port.",
    cover: "https://images.unsplash.com/photo-1502920917128-1aa500764ce0?auto=format&fit=crop&w=600&q=80",
    interest: "Culture",
    mapUrl: "https://goo.gl/maps/OkinawaDragon",
  },
  // Nagoya
  {
    id: 13,
    title: "Nagoya Castle Spring Festival",
    location: "Nagoya",
    date: "April 1 - 14, 2025",
    description: "Stroll among cherry trees and watch samurai parades at the castle.",
    cover: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80",
    interest: "Festival",
    mapUrl: "https://goo.gl/maps/NagoyaCastle",
  },
  {
    id: 14,
    title: "Nagoya Dome Illumination",
    location: "Nagoya",
    date: "November 23, 2025 - January 3, 2026",
    description: "Millions of LED lights, music, and winter exhibits at Nagoya Dome.",
    cover: "https://images.unsplash.com/photo-1512227331640-a217b5c8f8c5?auto=format&fit=crop&w=600&q=80",
    interest: "Culture",
    mapUrl: "https://goo.gl/maps/NagoyaDome",
  },
  // Yokohama
  {
    id: 15,
    title: "Yokohama Jazz Promenade",
    location: "Yokohama",
    date: "October 10 - 11, 2025",
    description: "100+ concerts and street jazz across Yokohama.",
    cover: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=600&q=80",
    interest: "Culture",
    mapUrl: "https://goo.gl/maps/YokohamaJazz",
  },
  {
    id: 16,
    title: "Yokohama Fireworks Festival",
    location: "Yokohama",
    date: "August 2, 2025",
    description: "Massive fireworks over Yokohama Bay, with food markets and music.",
    cover: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=600&q=80",
    interest: "Festival",
    mapUrl: "https://goo.gl/maps/YokohamaFireworks",
  },
  // Fukuoka
  {
    id: 17,
    title: "Fukuoka Gion Yamakasa",
    location: "Fukuoka",
    date: "July 1 - 15, 2025",
    description: "High-speed float racing and traditions in Hakata’s old town.",
    cover: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80",
    interest: "Festival",
    mapUrl: "https://goo.gl/maps/FukuokaGion",
  },
  {
    id: 18,
    title: "Fukuoka Light Fantasy",
    location: "Fukuoka",
    date: "December 1, 2025 - January 31, 2026",
    description: "Downtown Fukuoka sparkles with elaborate winter light displays.",
    cover: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
    interest: "Culture",
    mapUrl: "https://goo.gl/maps/FukuokaLight",
  },
  // Hiroshima
  {
    id: 19,
    title: "Hiroshima Peace Memorial Ceremony",
    location: "Hiroshima",
    date: "August 6, 2025",
    description: "Lantern floating and memorial for peace at Hiroshima Peace Park.",
    cover: "https://images.unsplash.com/photo-1454023492550-5696f8ff10e1?auto=format&fit=crop&w=600&q=80",
    interest: "Culture",
    mapUrl: "https://goo.gl/maps/HiroshimaPeace",
  },
  {
    id: 20,
    title: "Hiroshima Flower Festival",
    location: "Hiroshima",
    date: "May 3 - 5, 2025",
    description: "Flower-themed parades, floats, and markets across the city.",
    cover: "https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80",
    interest: "Festival",
    mapUrl: "https://goo.gl/maps/HiroshimaFlower",
  },
  // Kobe
  {
    id: 21,
    title: "Kobe Luminarie",
    location: "Kobe",
    date: "December 6 - 15, 2025",
    description: "Stunning winter light art with hundreds of thousands of lights downtown.",
    cover: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80",
    interest: "Culture",
    mapUrl: "https://goo.gl/maps/KobeLuminarie",
  },
  {
    id: 22,
    title: "Kobe Port Festival",
    location: "Kobe",
    date: "July 20 - 21, 2025",
    description: "Boat parades, harbor fireworks, and portside jazz concerts.",
    cover: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=600&q=80",
    interest: "Festival",
    mapUrl: "https://goo.gl/maps/KobePortFest",
  },
  // Hakone (NEW)
  {
    id: 23,
    title: "Hakone Daimyo Gyoretsu Parade",
    location: "Hakone",
    date: "November 3, 2025",
    description: "Edo-period lordly procession with samurai, costumes, and music.",
    cover: "https://images.unsplash.com/photo-1454023492550-5696f8ff10e1?auto=format&fit=crop&w=600&q=80",
    interest: "Culture",
    mapUrl: "https://goo.gl/maps/HakoneDaimyo",
  },
  {
    id: 24,
    title: "Hakone Ekiden Relay",
    location: "Hakone",
    date: "January 2 - 3, 2025",
    description: "Historic two-day university relay running race to Tokyo.",
    cover: "https://images.unsplash.com/photo-1465101162946-4377e57745c3?auto=format&fit=crop&w=600&q=80",
    interest: "Festival",
    mapUrl: "https://goo.gl/maps/HakoneEkiden",
  },
  // Sendai (NEW)
  {
    id: 25,
    title: "Sendai Tanabata Festival",
    location: "Sendai",
    date: "August 6 - 8, 2025",
    description: "Colorful paper streamers decorate central Sendai.",
    cover: "https://images.unsplash.com/photo-1512227331640-a217b5c8f8c5?auto=format&fit=crop&w=600&q=80",
    interest: "Festival",
    mapUrl: "https://goo.gl/maps/SendaiTanabata",
  },
  {
    id: 26,
    title: "Sendai Pageant of Starlight",
    location: "Sendai",
    date: "December 6 - 25, 2025",
    description: "Central avenue illuminated with thousands of LED lights.",
    cover: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80",
    interest: "Culture",
    mapUrl: "https://goo.gl/maps/SendaiStarlight",
  }
];
